WIP add parse_nmtran_messages function
A2-ai/nonmemtools pull request #1
Opened 2024-04-09 15:05 UTC by lanceferrer

In main:

![Screenshot 2024-04-09 at 11 03 01](https://github.com/A2-ai/nonmemtools/assets/153884017/cc4fc129-aba8-418f-8094-69262a7ac90a)

Output: 

![Screenshot 2024-04-09 at 11 03 11](https://github.com/A2-ai/nonmemtools/assets/153884017/5f7e2751-9b7d-4be5-a616-5a23a96389d2)

2024-04-09 15:14 UTC, dpastoor commented on src/rust/src/parsers/lst.rs
> +    LstData::new(false, false, covariance_step_run, None, 0, num_tables, 0)
it might be easier to initialize the LstData struct as mutable then just keep adding to it in that loop so you don't need to store temporary variables

so like for the num tables it would just be lst_data.num_tables = Some(number.parse().unwrap_or default())

2024-04-09 17:15 UTC, lanceferrer commented on src/rust/src/parsers/lst.rs
> +    LstData::new(false, false, covariance_step_run, None, 0, num_tables, 0)
got it.  I'll do that

2024-04-09 17:25 UTC, lanceferrer commented on src/rust/src/parsers/lst.rs
> +    LstData::new(false, false, covariance_step_run, None, 0, num_tables, 0)
pushed changes

2024-04-09 18:19 UTC, dpastoor requested changes
good progress!

2024-04-09 18:19 UTC, dpastoor commented on src/rust/src/parsers/lst.rs
> +                    .unwrap();
i think we should be a little careful around pure unwrapping - we probably need to like unwrap_or_.... for these. Like unwrapping gone wrong will cause a panic/crash, so what we want instead is if this _doesn't_ work it should fail in a way we find out about, but should fail gracefully. One way we can do that is use sentinel values, for example might do like `unwrap_or_else(-999)` 

where we can then document what those sentinel values are

2024-04-09 18:19 UTC, dpastoor commented on src/rust/src/parsers/lst.rs
> +                let yes_no = yes_no_pattern.find(&line).unwrap().as_str();
instead of finding the regex Yes or no, then checking for yes, we could use an is_match https://docs.rs/regex/latest/regex/struct.Regex.html#method.is_match

where we could match against yes - so then we more cleanly do like 

```
lst_data.theta_boundary_test_omitted = yes_re.match(&line)
```

which will be either true or false directly

2024-04-10 17:33 UTC, lanceferrer commented on src/rust/src/parsers/lst.rs
> +                let yes_no = yes_no_pattern.find(&line).unwrap().as_str();
do I need to do any error handling in that case?  Or is it fine without since a line containing something like "0DEFAULT THETA BOUNDARY TEST" will always end with a YES or a NO?

2024-04-11 03:36 UTC, dpastoor commented on src/rust/src/parsers/lst.rs
> +        Some(x) => x.as_str().trim_end().parse::<f64>().unwrap_or(-999.0),
we should separate the failure of parsing vs None - if values is -999 that comes out, is it cuz the parser failed for some reason or nothing was there.

might do -999, -998, etc for different values then (lightly) document meaning of each so a user if they get one of those back will be able to look up what the error means.

2024-04-18 13:34 UTC, dpastoor approved these changes
looks good thanks!

2024-04-18 13:34 UTC, merged